pull_request_rules:
  - name: automatic merge for dependeabot
    conditions:
      - and:
          - "author=dependabot[bot]"
          - or:
              - "title~=Bump coverlet.collector from"
              - "title~=Bump Microsoft.NET.Test.Sdk from"
              - "title~=Bump MSTest.TestAdapter from"
              - "title~=Bump MSTest.TestFramework from"
              - "title~=Bump Microsoft.CodeAnalysis.NetAnalyzers from"
    actions:
      merge:
        method: rebase
